Changing permissions to 755 for scripts.

diff --git a/scripts/dm-bookman b/scripts/dm-bookman
--- a/scripts/dm-bookman
+++ b/scripts/dm-bookman
@@ -2,12 +2,16 @@
 #
 # Script name: dm-bookman
 # Description: Search your qutebrowswer bookmarks and quickmarks.
-# Dependencies: dmenu, qutebrowser
+# Dependencies: dmenu, fzf, rofi, qutebrowser
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
 #               Simon Ingelsson
+#               Derek Taylor
 
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
 if [[  -f "${_path}/_dm-helper.sh" ]]; then
@@ -21,6 +25,9 @@ fi
 # script will not hit this if there is no config-file to load
 # shellcheck disable=SC1090
 source "$(get_config)"
+
+# Check if config has updates that should be displayed to the user
+check_updated_config
 
 _cache_dir="${HOME}/.cache/dm-bookman"
 _cache_file="${_cache_dir}/cache"
@@ -111,7 +118,7 @@ main() {
   # We use "printf '%s\n'" to format the array one item to a line.
   # The URLs are listed quickmarks, bookmarks and lastly history
   local choice=
-  choice=$( printf '%s\n' "${list}" "${histlist}" | sed '/^[[:space:]]*$/d' | ${DMENU} "${DMBROWSER} open:" "$@" )
+  choice=$( printf '%s\n' "${list}" "${histlist}" | sed '/^[[:space:]]*$/d' | ${MENU} "${DMBROWSER} open:" "$@" )
 
   # What to do if the separator is chosen from the list.
   # We simply launch qutebrowser without any URL arguments.
@@ -126,5 +133,26 @@ main() {
   fi
 }
 
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-documents b/scripts/dm-documents
--- a/scripts/dm-documents
+++ b/scripts/dm-documents
@@ -1,11 +1,12 @@
 #!/bin/bash
 #
 # Script name: dm-documents
-# Description: Search for a process to kill.
-# Dependencies: dmenu, zathura
+# Description: Search for PDFs to open.
+# Dependencies: dmenu, fzf, rofi, zathura
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
-# Contributors: Derek Taylor, HostGrady
+# Contributors: Derek Taylor
+#               HostGrady
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
@@ -25,6 +26,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main(){
   # PDF_VIEWER=zathura
   files="$(find "$HOME" -maxdepth 4 -iname "*.pdf")"
@@ -36,7 +40,7 @@ main(){
         -e 's/Images/Img/g' \
         -e 's/.pdf//g' | \
         sort -g | \
-      ${DMENU} "File: " "$@") || exit 1
+      ${MENU} "File: " "$@") || exit 1
   if [ "$choice" ]; then
       file=$( printf '%s' "$choice" | \
         sed -e 's/Dcs/Documents/g' \
@@ -50,4 +54,26 @@ main(){
   fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-eq-profiles b/scripts/dm-eq-profiles
--- a/scripts/dm-eq-profiles
+++ b/scripts/dm-eq-profiles
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 #
 # Script name: dm-eq-profiles
-# Description: A dmenu script allowing you to switch between predefined equalizer profiles easily.
-# Dependencies: dmenu, easyeffects
+# Description: Allows you to switch between predefined equalizer profiles easily.
+# Dependencies: dmenu, fzf, rofi, easyeffects
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Allen (aaw3_)
+#               Derek Taylor
 
 # Note: Avoid using commas in preset names otherwise it will cause errors when trying to parse the presets list
 
@@ -26,6 +27,9 @@ fi
 # script will not hit this if there is no config-file to load
 # shellcheck disable=SC1090
 source "$(get_config)"
+
+# Check if config has updates that should be displayed to the user
+check_updated_config
 
 main() {
   # shellcheck disable=SC2154
@@ -61,12 +65,33 @@ main() {
   #echo $OutputProfiles
   #echo $InputProfiles
 
-
-  _profile=$(printf '%s\n' "${eq_profiles[@]}" | ${DMENU} "Choose a profile:" "$@") || exit 1
+  _profile=$(printf '%s\n' "${eq_profiles[@]}" | ${MENU} "Choose a profile:" "$@") || exit 1
 
   if [[ $_profile == "Quit" ]]; then echo "Program Terminated" && exit 0; fi
 
   easyeffects -l "${_profile:3}"
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-hub b/scripts/dm-hub
--- a/scripts/dm-hub
+++ b/scripts/dm-hub
@@ -1,22 +1,29 @@
 #!/usr/bin/env bash
 #
 # Script name: dm-hub
-# Description: a hub that you can execute all the other scripts from
-# Dependencies: dmenu, executable dmscripts, all the dependancies from dmscripts
-# GitLab: https://www.gitlab.com/dwt1/hub
+# Description: A hub allowing you to execute all the other dmscripts.
+# Dependencies: dmenu, fzf, rofi
+# GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: n-e0
 #               Simon Ingelsson
+#               Derek Taylor
 
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 
 _path=$(dirname "$(realpath "$0")")
 [[ ! -f "${_path}/_dm-helper.sh" ]] && echo "No helper-script found"
 # shellcheck disable=SC1090,SC1091
 source "${_path}/_dm-helper.sh"
+
+# script will not hit this if there is no config-file to load
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
 check_updated_config
 
 function main() {
@@ -33,7 +40,7 @@ function main() {
         _scripts[${script_name}]="${script}"
     done< <(find "${_path}" -type f -regex ".*/dm-.*" -print0)
 
-    choice=$(printf '%s\n' "${!_scripts[@]}" | sort | ${DMENU} 'Run Script:' "$@")
+    choice=$(printf '%s\n' "${!_scripts[@]}" | sort | ${MENU} 'Run Script:' "$@")
 
     if [ "${choice}" ]; then
         bash "$(printf '%s\n' "${_scripts["${choice}"]}" | awk '{print $1}')" "$@"
@@ -42,4 +49,26 @@ function main() {
     fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-ip b/scripts/dm-ip
--- a/scripts/dm-ip
+++ b/scripts/dm-ip
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
 
 # Script name: dm-ip
-# Description: Get IP from interface (or external)
-# Dependencies: dmenu, dig, ip, jq
+# Description: Get IP from interface or external.
+# Dependencies: dmenu, fzf, rofi, dig, ip, jq
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Simon Ingelsson
+#               Derek Taylor
 
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
 if [[  -f "${_path}/_dm-helper.sh" ]]; then
@@ -21,6 +25,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main() {
   declare -A _ips
 
@@ -31,10 +38,32 @@ main() {
     _ips[${_iface%:*}]="${_iface##*:}"
   done
 
-  selected="$(printf '%s\n' "${!_ips[@]}" | ${DMENU} "ips:" "$@")"
+  selected="$(printf '%s\n' "${!_ips[@]}" | ${MENU} "ips:" "$@")"
   [ -z "${selected}" ] && exit 1
   echo "${_ips["${selected}"]}" | cp2cb 
   notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-kill b/scripts/dm-kill
--- a/scripts/dm-kill
+++ b/scripts/dm-kill
@@ -2,15 +2,15 @@
 #
 # Script name: dm-kill
 # Description: Search for a process to kill.
-# Dependencies: dmenu
+# Dependencies: dmenu, fzf, rofi
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
-# Contributors: Derek Taylor, HostGrady
+# Contributors: Derek Taylor
+#               HostGrady
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
 # get hidden bugs that are hard to discover.
-
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
 if [[  -f "${_path}/_dm-helper.sh" ]]; then
@@ -25,19 +25,22 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main() {
     # Running ps to get running processes and display in dmenu.
     # In this script we use a variable called $DMENU, in your scripts, you
     # should just write dmenu or rofi or whatever launcher you use.
     selected="$(ps --user "$USER" -F | \
-                ${DMENU} "Search for process to kill:" "$@" | \
+                ${MENU} "Search for process to kill:" "$@" | \
                 awk '{print $2" "$11}')";
 
     # Nested 'if' statements.  The outer 'if' statement is what to do
     # when we select one of the 'selected' options listed in dmenu.
     if [[ -n $selected ]]; then
         # Piping No/Yes into dmenu as a safety measure, in case you
-        answer="$(echo -e "No\nYes" | ${DMENU} "Kill $selected?" "$@")"
+        answer="$(echo -e "No\nYes" | ${MENU} "Kill $selected?" "$@")"
 
         if [[ $answer == "Yes" ]]; then
             # This echo command prints everything before the first space.
@@ -49,9 +52,31 @@ main() {
         else
 	    # We want this script to exit with a 1 and not 0 because 1 means
 	    # an error, so this can be handled by other scripts better
-            echo "Program terminated." && exit 1
+            echo "User choose not to kill a process." && exit 1
         fi
     fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-maim b/scripts/dm-maim
--- a/scripts/dm-maim
+++ b/scripts/dm-maim
@@ -2,13 +2,12 @@
 #
 # Script name: dm-maim
 # Description: Choose type of screenshot to take with maim.
-# Dependencies: dmenu, maim, tee, xdotool, xclip, xrandr
+# Dependencies: dmenu, fzf, rofi, maim, tee, xdotool, xclip, xrandr
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
 #               Simon Ingelsson
 #               Steven Hall
-
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
@@ -28,6 +27,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 # Defining our config location
+
+# Check if config has updates that should be displayed to the user
+check_updated_config
 
 get_timestamp() {
   date '+%Y%m%d-%H%M%S'
@@ -87,7 +89,7 @@ main() {
   done
   unset IFS
 
-  target=$(printf '%s\n' "${modes[@]}" | ${DMENU} 'Take screenshot of:' "$@") || exit 1
+  target=$(printf '%s\n' "${modes[@]}" | ${MENU} 'Take screenshot of:' "$@") || exit 1
   case "$target" in
     'Fullscreen')
       _file_type="full"
@@ -107,7 +109,7 @@ main() {
     ;;
   esac
 
-  delay=$(printf '%s\n' "$(seq 0 5)" | ${DMENU} 'Delay (in seconds):' "$@" ) || exit 1
+  delay=$(printf '%s\n' "$(seq 0 5)" | ${MENU} 'Delay (in seconds):' "$@" ) || exit 1
   if [ ! "${delay}" -eq "0" ]; then
     _maim_args="${_maim_args} --delay=${delay}"
   else
@@ -116,7 +118,7 @@ main() {
 
   _maim_args="${_maim_args} -q"
   local destination=( "File" "Clipboard" "Both" )
-  dest=$(printf '%s\n' "${destination[@]}" | ${DMENU} 'Destination:' "$@" ) || exit 1
+  dest=$(printf '%s\n' "${destination[@]}" | ${MENU} 'Destination:' "$@" ) || exit 1
   case "$dest" in
     'File')
       # shellcheck disable=SC2086,SC2154
@@ -140,4 +142,26 @@ main() {
 
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-music b/scripts/dm-music
--- a/scripts/dm-music
+++ b/scripts/dm-music
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
 # Script name: dm-music
-# Description: Play music using dmenu, mpd and mpc.
-# Dependencies: dmenu, mpd, mpc, wildmidi, timidity++
+# Description: Play music using mpd and mpc.
+# Dependencies: dmenu, fzf, rofi, mpd, mpc, wildmidi, timidity++
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Murtaza Udaipurwala
@@ -47,23 +47,12 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
-help(){
-    printf "Run dm-music without any arguments for all available music\n
-    dm-music [options]
-    -h\tdisplays this help page
-    -q\tQueue a playlist
-    -p\tSelect music for the queued playlist\n
-    ### Some useful mpc command
-    mpc toggle\t\t\ttoggle between pause and play state
-    mpc next\t\t\tgo to next track
-    mpc prev\t\t\tgo to prev track
-    mpc seekthrough +00:00:10\tseek 10s forward
-    mpc seekthrough -00:00:10\tseek 10s backward\n"
-}
+# Check if config has updates that should be displayed to the user
+check_updated_config
 
 play(){
     mpc crop > /dev/null 2>&1
-    music="$(mpc listall | ${DMENU} "Music to play")" || exit 1
+    music="$(mpc listall | ${MENU} "Music to play")" || exit 1
     mpc -q add "$music"
     mpc del 0 > /dev/null 2>&1
     mpc play
@@ -71,7 +60,7 @@ play(){
 }
 
 queuePlaylist(){
-    playlist="$(mpc lsplaylists | ${DMENU} "Your playlists")" || exit 1
+    playlist="$(mpc lsplaylists | ${MENU} "Your playlists")" || exit 1
     mpc -q clear
     mpc load "$playlist"
     mpc -q play 1
@@ -81,21 +70,62 @@ queuePlaylist(){
 currentPlaylist(){
     playlist="$(cat "${HOME}/.cache/current_playlist")"
     music_list="$(mpc playlist "${playlist}")"
-    music="$(echo "${music_list}" | ${DMENU} "Music to play")" || exit 1
+    music="$(echo "${music_list}" | ${MENU} "Music to play")" || exit 1
     mpc -q clear
     mpc load "${playlist}" > /dev/null 2>&1
     mpc play "$(echo "${music_list}" | awk -v pattern="$music" '$0 ~ pattern { print NR; exit }')"
 }
 
+# We write a unique help function for dm-music since it has
+# more options than the typical dmscript.
+help(){
+    printf '%s' "Usage: $(basename "$0") [options]
+$(grep '^# Description: ' "$0"  | sed 's/# Description: /Description: /g')
+$(grep '^# Dependencies: ' "$0"  | sed 's/# Dependencies: /Dependencies: /g')
+
+The folowing OPTIONS are accepted:
+    -h  displays this help page
+    -d  runs the script using 'dmenu'
+    -f  runs the script using 'fzf'
+    -r  runs the script using 'rofi'
+    -q  queue a playlist
+    -p  select music for the queued playlist
+
+Some useful mpc commands:
+    mpc toggle\t\t\ttoggle between pause and play state
+    mpc next\t\t\tgo to next track
+    mpc prev\t\t\tgo to prev track
+    mpc seekthrough +00:00:10\tseek 10s forward
+    mpc seekthrough -00:00:10\tseek 10s backward
+
+Running" " $(basename "$0") " "without any argument defaults to using 'dmenu'
+Run 'man dmscripts' for more information"
+
+}
+
 noOpt=1
-while getopts "hqpt" arg 2>/dev/null; do
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrhqpt" arg 2>/dev/null; do
     case "${arg}" in
-        h) help ;;
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && play ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && play ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && play ;;
         q) queuePlaylist ;;
         p) currentPlaylist ;;
         t) mpc toggle ;;
-        *) printf "invalid option\nType dm-music -h for help\n" ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
-[ $noOpt = 1 ] && play
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && play "$@"
diff --git a/scripts/dm-radio b/scripts/dm-radio
--- a/scripts/dm-radio
+++ b/scripts/dm-radio
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
 # Script name: dm-radio
-# Description: Choose between online radio stations with dmenu.
-# Dependencies: dmenu, mpv, notify-send, youtube-dl
+# Description: Choose between online radio stations; stations defined in dmscripts config.
+# Dependencies: dmenu, fzf, rofi, mpv, notify-send, youtube-dl
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
@@ -25,6 +25,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 menu() {
   printf '%s\n' "Quit"
   # As this is loaded from other file it is technically not defined.
@@ -43,7 +46,7 @@ end_radio() {
 
 main() {
   # Choosing a radio station from array sourced in 'config'.
-  choice=$(menu | ${DMENU} 'Choose radio station:' "$@") || exit 1
+  choice=$(menu | ${MENU} 'Choose radio station:' "$@") || exit 1
 
   case $choice in
     Quit)
@@ -61,4 +64,26 @@ main() {
 
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-reddit b/scripts/dm-reddit
--- a/scripts/dm-reddit
+++ b/scripts/dm-reddit
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
 # Script name: dm-reddit
-# Description: Dmenu as a reddit viewer using reddio.
-# Dependencies: dmenu, reddio, yad
+# Description: A simple reddit viewer using reddio.
+# Dependencies: dmenu, fzf, rofi, reddio, yad
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
@@ -27,16 +27,19 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main() {
   # Picking a subreddit from the above reddit_list.
   # As this is loaded from other file it is technically not defined
   # shellcheck disable=SC2154
   reddit_list+=( "Quit" )
-  _subreddit=$(printf '%s\n' "${reddit_list[@]}" | ${DMENU} "Choose a subreddit:" "$@") || exit 1
+  _subreddit=$(printf '%s\n' "${reddit_list[@]}" | ${MENU} "Choose a subreddit:" "$@") || exit 1
 
   # Show the last 20 posts (titles and ids) from the chosen subreddit.
   post_title=$(bash reddio print -f '$num. $title $id$nl' -l 20 "$_subreddit" | \
-  ${DMENU} 'Last 20 posts on '"$_subreddit" "$@")
+  ${MENU} 'Last 20 posts on '"$_subreddit" "$@")
 
   # Display contents of chosen post in a yad text box.
   post_id=$(printf '%s\n' "${post_title##* }")
@@ -44,4 +47,26 @@ main() {
   yad --text-info --height=600 --width=600 || exit 1
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-usbmount b/scripts/dm-usbmount
--- a/scripts/dm-usbmount
+++ b/scripts/dm-usbmount
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
 # script name: dm-usbmount
-# Description: mount/unmount usb drives using dmenu. No fancy daemon required
-# Dependencies : dmenu, udisks2
+# Description: Mount/unmount usb drives using dmenu. No fancy daemon required.
+# Dependencies: dmenu, fzf, rofi, udisks2
 # Author: Murtaza Udaipurwala
+#               Derek Taylor
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
@@ -23,12 +24,25 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 help(){
-    printf 'dm-usbmount [options]\n
-    -h\tDisplays this help menu
-    -m\tMount usb drive
-    -u\tUnmount usb drive\n
-    Drives are mounted at /run/media\n'
+    printf '%s' "Usage: $(basename "$0") [options]
+$(grep '^# Description: ' "$0"  | sed 's/# Description: /Description: /g')
+$(grep '^# Dependencies: ' "$0"  | sed 's/# Dependencies: /Dependencies: /g')
+
+The folowing OPTIONS are accepted:
+    -h  displays this help page
+    -d  mount using 'dmenu'
+    -D  umount using 'dmenu'
+    -f  mount using 'fzf'
+    -F  umount using 'fzf'
+    -r  mount using 'rofi'
+    -R  umount using 'rofi'
+
+Running" " $(basename "$0") " "without any argument displays this help text.
+Run 'man dmscripts' for more information"
 }
 
 driveCount(){
@@ -57,7 +71,7 @@ mount(){
     driveCount "$mountable"
     [ "$count" = "1" ] && options="$mountable" || options="$mountable\nall"
 
-    chosen="$(printf '%s' "$options" | ${DMENU} "Drive to mount?")" || exit 1
+    chosen="$(printf '%s' "$options" | ${MENU} "Drive to mount?")" || exit 1
     if [ "$chosen" = "all" ]; then
        mountAll 
     else 
@@ -75,7 +89,7 @@ unmount(){
     # [ "$count" = "1" ] && options="$mounted" || options="$mounted\nall"
     [ "$count" = "1" ] && options="${mounted%%* }" || options="${mounted%%* }\nall"
 
-    chosen="$(printf '%s' "${options}" | ${DMENU} "Drive to unmount?")"
+    chosen="$(printf '%s' "${options}" | ${MENU} "Drive to unmount?")"
     if [ "$chosen" = "all" ] ; then 
        unmountAll 
    else
@@ -83,11 +97,35 @@ unmount(){
     fi
 }
 
-while getopts "hmu" arg 2>/dev/null; do
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dDfFrRh" arg 2>/dev/null; do
     case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && mount ;;
+        D) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && unmount ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && mount ;;
+        F) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && unmount ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && mount ;;
+        R) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && unmount ;;
         h) help ;;
-        m) mount ;;
-        u) unmount ;;
-        *) printf "invalid option\nType dm-usbmount -h for help" ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
+    noOpt=0
 done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && help "$@"
diff --git a/scripts/dm-websearch b/scripts/dm-websearch
--- a/scripts/dm-websearch
+++ b/scripts/dm-websearch
@@ -2,7 +2,7 @@
 #
 # Script name: dm-websearch
 # Description: Search various search engines (inspired by surfraw).
-# Dependencies: dmenu and brave
+# Dependencies: dmenu, fzf, rofi, brave (change DMMBROWSER in dmscripts config if using another browser)
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: Derek Taylor
@@ -28,17 +28,19 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
 
 main() {
   # As this is loaded from other file it is technically not defined
   # shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
-  engine=$(printf '%s\n' "${!websearch[@]}" | sort | ${DMENU} 'Choose search engine:' "$@") || exit 1
+  engine=$(printf '%s\n' "${!websearch[@]}" | sort | ${MENU} 'Choose search engine:' "$@") || exit 1
 
   # Getting the URL of the search engine we chose.
   url="${websearch["${engine}"]}"
 
   # Searching the chosen engine.
-  query=$(echo "$engine" | ${DMENU} 'Enter search query:')
+  query=$(printf '%s' "$engine" | ${MENU} 'Enter search query:')
 
   query="$(echo -n "${query}" | jq -s -R -r @uri)"
   # Display search results in web browser
@@ -46,4 +48,26 @@ main() {
   ${DMBROWSER} "${url}${query}"
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-wifi b/scripts/dm-wifi
--- a/scripts/dm-wifi
+++ b/scripts/dm-wifi
@@ -2,9 +2,15 @@
 #
 # script name: dm-wifi
 # Description: Connect to wifi using dmenu
-# Dependencies: dmenu, nmcli, Any Nerd Font
+# Dependencies: dmenu, fzf, rofi, nmcli, Any Nerd Font
+# GitLab: https://www.gitlab.com/dwt1/dmscripts
+# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributor: WitherCubes
+#              Derek Taylor
 
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
 if [[  -f "${_path}/_dm-helper.sh" ]]; then
@@ -19,10 +25,13 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main() {
   # TODO: Fix cut line at some point
-  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} "Select Wifi  :" | cut -d' ' -f1)
-  pass=$(echo "" | ${DMENU} "Enter Password  :")
+  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${MENU} "Select Wifi  :" | cut -d' ' -f1)
+  pass=$(echo "" | ${MENU} "Enter Password  :")
   # We are disabling a shellcheck warning about using && and || as it doesn't apply here.
   # shellcheck disable=SC2015
   [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
@@ -34,4 +43,26 @@ main() {
   fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-wiki b/scripts/dm-wiki
--- a/scripts/dm-wiki
+++ b/scripts/dm-wiki
@@ -5,7 +5,8 @@
 # Dependencies: dmenu, arch-wiki-docs
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
-# Contributors: Derek Taylor, marvhus
+# Contributors: Derek Taylor
+#               marvhus
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
@@ -24,6 +25,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 wikidir="/usr/share/doc/arch-wiki/html/"
 lang=""
 
@@ -32,7 +36,7 @@ languages() {
     choice=$(printf '%s\n' "${langs[@]}" | \
         sed 's/.*\///' | \
         sort -g | \
-        ${DMENU} 'Language: ' "$@") || exit 1
+        ${MENU} 'Language: ' "$@") || exit 1
 
     if [ "$choice" ]; then
         lang=$(printf '%s\n' "${choice}/")
@@ -48,7 +52,7 @@ wikipages() {
            cut -d '/' -f8- | \
            sed -e 's/_/ /g' -e 's/.html//g' | \
            sort -g | \
-           ${DMENU} 'Arch Wiki Docs: ' "$@") || exit 1
+           ${MENU} 'Arch Wiki Docs: ' "$@") || exit 1
 
     if [ "$choice" ]; then
         article=$(printf '%s\n' "${wikidir}${lang}${choice}.html" | sed 's/ /_/g')
@@ -58,4 +62,26 @@ wikipages() {
     fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages "$@"
diff --git a/scripts/dm-youtube b/scripts/dm-youtube
--- a/scripts/dm-youtube
+++ b/scripts/dm-youtube
@@ -6,8 +6,11 @@
 # Gitlab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: HostGrady
+#               Derek Taylor
 
-# pipefail setup
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
@@ -23,6 +26,9 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
+check_updated_config
+
 main() {
   local _feed_url _channel _video
   local _channel_id _video_id _video_list
@@ -30,7 +36,7 @@ main() {
   # Sorts the array and lets you select a channel with dmenu
   # As this is loaded from other file it is technically not defined
   # shellcheck disable=SC2154
-  _channel=$(printf '%s\n' "${!youtube_channels[@]}" | sort | ${DMENU} 'Select Channel:' "$@")
+  _channel=$(printf '%s\n' "${!youtube_channels[@]}" | sort | ${MENU} 'Select Channel:' "$@")
 
   # The way it's done here is most effective, it searchs for "=" then it takes
   # everything before the = sign and leaves us with our variable used in the
@@ -40,7 +46,7 @@ main() {
   # parse rss
   _video_list=$(parse_rss "$(curl -s "${_feed_url}")" )
 
-  _video=$(printf '%s\n' "${_video_list}" | sort -r | ${DMENU} 'Select Video' "$@")
+  _video=$(printf '%s\n' "${_video_list}" | sort -r | ${MENU} 'Select Video' "$@")
   _video_id=$(echo "${_video}" | cut -d'|' -f2 | sed -e 's/^[ \t]*//')
 
   if [[ -n ${_video_id} ]]; then
@@ -50,4 +56,26 @@ main() {
   fi
 }
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
+
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
