Update formatting

diff --git a/scripts/dm-colpick b/scripts/dm-colpick
--- a/scripts/dm-colpick
+++ b/scripts/dm-colpick
@@ -16,12 +16,12 @@
 set -euo pipefail
 
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-  # shellcheck disable=SC1090
-  echo "No helper-script found"
+    # shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -32,11 +32,11 @@ source "$(get_config)"
 check_updated_config
 
 main() {
-  # As this is loaded from other file it is technically not defined
-  # shellcheck disable=SC2154
-  selected="$(printf '%s\n' "${!colpick_list[@]}" | ${MENU} "color:" "$@")"
-  [ -z "${selected}" ] && exit 1
-  echo "${colpick_list["${selected}"]}" | cp2cb
+    # As this is loaded from other file it is technically not defined
+    # shellcheck disable=SC2154
+    selected="$(printf '%s\n' "${!colpick_list[@]}" | ${MENU} "color:" "$@")"
+    [ -z "${selected}" ] && exit 1
+    echo "${colpick_list["${selected}"]}" | cp2cb
 }
 
 noOpt=1
@@ -45,17 +45,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@" ;;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
diff --git a/scripts/dm-eq-profiles b/scripts/dm-eq-profiles
--- a/scripts/dm-eq-profiles
+++ b/scripts/dm-eq-profiles
@@ -16,12 +16,12 @@
 set -euo pipefail
 
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-   shellcheck disable=SC1090
-  echo "No helper-script found"
+    shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -32,44 +32,42 @@ source "$(get_config)"
 check_updated_config
 
 main() {
-  # shellcheck disable=SC2154
+    # shellcheck disable=SC2154
 
-  #Retrieve profiles form easyeffects
-  AllProfiles=$(easyeffects -p)
+    #Retrieve profiles form easyeffects
+    AllProfiles=$(easyeffects -p)
 
-  #Separate profiles
-  OutputProfiles=$(echo "${AllProfiles}" | head -1)
-  InputProfiles=$(echo "${AllProfiles}" | tail -1)
+    #Separate profiles
+    OutputProfiles=$(echo "${AllProfiles}" | head -1)
+    InputProfiles=$(echo "${AllProfiles}" | tail -1)
 
-  #Trim the beginning of I/O profiles
-  OutputProfiles="${OutputProfiles:16}"
-  InputProfiles="${InputProfiles:15}"
+    #Trim the beginning of I/O profiles
+    OutputProfiles="${OutputProfiles:16}"
+    InputProfiles="${InputProfiles:15}"
 
-  IFS=',' read -r -a OutputArray <<< "${OutputProfiles}"
-  IFS=',' read -r -a InputArray <<< "${InputProfiles}"
+    IFS=',' read -r -a OutputArray <<<"${OutputProfiles}"
+    IFS=',' read -r -a InputArray <<<"${InputProfiles}"
 
-  declare -a eq_profiles
+    declare -a eq_profiles
 
-  for element in "${OutputArray[@]}"
-  do
-      eq_profiles+=( "O: ${element}" )
-  done
+    for element in "${OutputArray[@]}"; do
+        eq_profiles+=("O: ${element}")
+    done
 
-  for element in "${InputArray[@]}"
-  do
-      eq_profiles+=( "I: ${element}" )
-  done
+    for element in "${InputArray[@]}"; do
+        eq_profiles+=("I: ${element}")
+    done
 
-  eq_profiles+=( "Quit" )
+    eq_profiles+=("Quit")
 
-  #echo $OutputProfiles
-  #echo $InputProfiles
+    #echo $OutputProfiles
+    #echo $InputProfiles
 
-  _profile=$(printf '%s\n' "${eq_profiles[@]}" | ${MENU} "Choose a profile:" "$@") || exit 1
+    _profile=$(printf '%s\n' "${eq_profiles[@]}" | ${MENU} "Choose a profile:" "$@") || exit 1
 
-  if [[ $_profile == "Quit" ]]; then echo "Program Terminated" && exit 0; fi
+    if [[ $_profile == "Quit" ]]; then echo "Program Terminated" && exit 0; fi
 
-  easyeffects -l "${_profile:3}"
+    easyeffects -l "${_profile:3}"
 }
 
 noOpt=1
@@ -78,17 +76,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@";;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
diff --git a/scripts/dm-ip b/scripts/dm-ip
--- a/scripts/dm-ip
+++ b/scripts/dm-ip
@@ -13,12 +13,12 @@
 # get hidden bugs that are hard to discover.
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-  # shellcheck disable=SC1090
-  echo "No helper-script found"
+    # shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -29,19 +29,19 @@ source "$(get_config)"
 check_updated_config
 
 main() {
-  declare -A _ips
+    declare -A _ips
 
-  _external=$(dig +short myip.opendns.com @resolver1.opendns.com)
-  _ips[external]="${_external}"
+    _external=$(dig +short myip.opendns.com @resolver1.opendns.com)
+    _ips[external]="${_external}"
 
-  for _iface in $(ip -4 -j addr | jq -r '.[] |{ name: .ifname, ip: .addr_info[].local} | join(":")') ; do
-    _ips[${_iface%:*}]="${_iface##*:}"
-  done
+    for _iface in $(ip -4 -j addr | jq -r '.[] |{ name: .ifname, ip: .addr_info[].local} | join(":")'); do
+        _ips[${_iface%:*}]="${_iface##*:}"
+    done
 
-  selected="$(printf '%s\n' "${!_ips[@]}" | ${MENU} "ips:" "$@")"
-  [ -z "${selected}" ] && exit 1
-  echo "${_ips["${selected}"]}" | cp2cb 
-  notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
+    selected="$(printf '%s\n' "${!_ips[@]}" | ${MENU} "ips:" "$@")"
+    [ -z "${selected}" ] && exit 1
+    echo "${_ips["${selected}"]}" | cp2cb
+    notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
 }
 
 noOpt=1
@@ -50,17 +50,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@";;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
diff --git a/scripts/dm-logout b/scripts/dm-logout
--- a/scripts/dm-logout
+++ b/scripts/dm-logout
@@ -5,7 +5,7 @@
 # Dependencies: dmenu, fzf, rofi, systemd, slock, notify-send
 # GitLab: https://www.gitlab.com/dwt1/dmscripts
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
-# Contributors: Derek Taylor, 
+# Contributors: Derek Taylor,
 #               Simon Ingelsson
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
@@ -14,12 +14,12 @@
 set -euo pipefail
 
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-  # shellcheck disable=SC1090
-  echo "No helper-script found"
+    # shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -36,25 +36,24 @@ if [[ ${TERM} == 'dumb' ]]; then
     _out="notify-send"
 fi
 
-output(){
+output() {
     ${_out} "dm-logout" "$@"
 }
 
 main() {
     # An array of options to choose.
     declare -a options=(
-    "Lock screen"
-    "Logout"
-    "Reboot"
-    "Shutdown"
-    "Suspend"
-    "Quit"
+        "Lock screen"
+        "Logout"
+        "Reboot"
+        "Shutdown"
+        "Suspend"
+        "Quit"
     )
 
     # look up what managers are used (makes it more dynamic)
     declare -a MANAGERS
-    while IFS= read -r manager
-    do
+    while IFS= read -r manager; do
         MANAGERS+=("${manager,,}")
     done < <(grep-desktop)
     # Original code, used as a refrence and as backup
@@ -66,47 +65,47 @@ main() {
 
     # What to do when/if we choose one of the options.
     case $choice in
-        'Logout')
-            if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}" )" == "Yes" ]]; then
-                for manager in "${MANAGERS[@]}"; do 
-                    killall "${manager}" || output "Process ${manager} was not running."
-                done
-            else
-                output "User chose not to logout." && exit 1
-            fi
-            ;;
-        'Lock screen')
-            # shellcheck disable=SC2154
-            ${logout_locker}
-            ;;
-        'Reboot')
-            if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}" )" == "Yes" ]]; then
-                systemctl reboot
-            else
-                output "User chose not to reboot." && exit 0
-            fi
-            ;;
-        'Shutdown')
-            if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}" )" == "Yes" ]]; then
-                systemctl poweroff
-            else
-                output "User chose not to shutdown." && exit 0
-            fi
-            ;;
-        'Suspend')
-            if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}" )" == "Yes" ]]; then
-                systemctl suspend
-            else
-                output "User chose not to suspend." && exit 0
-            fi
-            ;;
-        'Quit')
-            output "Program terminated." && exit 0
+    'Logout')
+        if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}")" == "Yes" ]]; then
+            for manager in "${MANAGERS[@]}"; do
+                killall "${manager}" || output "Process ${manager} was not running."
+            done
+        else
+            output "User chose not to logout." && exit 1
+        fi
         ;;
-        # It is a common practice to use the wildcard asterisk symbol (*) as a final
-        # pattern to define the default case. This pattern will always match.
-        *)
-            exit 0
+    'Lock screen')
+        # shellcheck disable=SC2154
+        ${logout_locker}
+        ;;
+    'Reboot')
+        if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}")" == "Yes" ]]; then
+            systemctl reboot
+        else
+            output "User chose not to reboot." && exit 0
+        fi
+        ;;
+    'Shutdown')
+        if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}")" == "Yes" ]]; then
+            systemctl poweroff
+        else
+            output "User chose not to shutdown." && exit 0
+        fi
+        ;;
+    'Suspend')
+        if [[ "$(echo -e "No\nYes" | ${MENU} "${choice}?" "${@}")" == "Yes" ]]; then
+            systemctl suspend
+        else
+            output "User chose not to suspend." && exit 0
+        fi
+        ;;
+    'Quit')
+        output "Program terminated." && exit 0
+        ;;
+    # It is a common practice to use the wildcard asterisk symbol (*) as a final
+    # pattern to define the default case. This pattern will always match.
+    *)
+        exit 0
         ;;
     esac
 
@@ -118,17 +117,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@";;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
diff --git a/scripts/dm-maim b/scripts/dm-maim
--- a/scripts/dm-maim
+++ b/scripts/dm-maim
@@ -15,12 +15,12 @@
 set -euo pipefail
 
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-  # shellcheck disable=SC1090
-  echo "No helper-script found"
+    # shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -32,113 +32,113 @@ source "$(get_config)"
 check_updated_config
 
 get_timestamp() {
-  date '+%Y%m%d-%H%M%S'
+    date '+%Y%m%d-%H%M%S'
 }
 
 # local version of cp2cb is needed to account for dm-maim's specific usage
 
 cp2cb-maim() {
-  case "$XDG_SESSION_TYPE" in
-    'x11') xclip -selection clipboard -t image/png;;
-    'wayland') wl-copy -t image/png;;
-    *) err "Unknown display server";;
-  esac
+    case "$XDG_SESSION_TYPE" in
+    'x11') xclip -selection clipboard -t image/png ;;
+    'wayland') wl-copy -t image/png ;;
+    *) err "Unknown display server" ;;
+    esac
 }
 
 main() {
-  local _maim_args=""
-  local _file_type=""
-  # Makes sure the directory exists.
-  # shellcheck disable=SC2154
-  mkdir -p "${maim_dir}"
+    local _maim_args=""
+    local _file_type=""
+    # Makes sure the directory exists.
+    # shellcheck disable=SC2154
+    mkdir -p "${maim_dir}"
 
-  declare -a modes=(
-  "Fullscreen"
-  "Active window"
-  "Selected region"
-  )
-  # Get monitors and their settings for maim
-  
-  # Grepping with awk here, /+/ means return only lines with +, ie grep
-  # On that note, this could probably be written more efficiently in one awk
-  # command as opposed to two however I am not an awk guru soo...
-  _displays=$(xrandr --listactivemonitors | awk '/+/ {print $4, $3}' | awk -F'[x/+* ]' '{print $1,$2"x"$4"+"$6"+"$7}')
+    declare -a modes=(
+        "Fullscreen"
+        "Active window"
+        "Selected region"
+    )
+    # Get monitors and their settings for maim
 
-  # Add monitor data
+    # Grepping with awk here, /+/ means return only lines with +, ie grep
+    # On that note, this could probably be written more efficiently in one awk
+    # command as opposed to two however I am not an awk guru soo...
+    _displays=$(xrandr --listactivemonitors | awk '/+/ {print $4, $3}' | awk -F'[x/+* ]' '{print $1,$2"x"$4"+"$6"+"$7}')
 
-  # If I'm understanding correctly this should work however bear in mind I run
-  # a single monitor setup so some testing is needed before this is merged
-  IFS=$'\n'
-  declare -A _display_mode
-  for i in ${_displays}; do
-  # These lines are commented because I believe it can be done faster with
-  # some different syntax. Luke smith has done a video about this efficiency
-  # and it has been used in earlier scripts
+    # Add monitor data
 
-  # name=$(echo "${i}" | awk '{print $1}')
-  # rest="$(echo "${i}" | awk '{print $2}')"
+    # If I'm understanding correctly this should work however bear in mind I run
+    # a single monitor setup so some testing is needed before this is merged
+    IFS=$'\n'
+    declare -A _display_mode
+    for i in ${_displays}; do
+        # These lines are commented because I believe it can be done faster with
+        # some different syntax. Luke smith has done a video about this efficiency
+        # and it has been used in earlier scripts
 
-  # Think of "i%% *" as awk '{print $1}' in this case, it isn't a 1 to 1 but
-  # for this example it does the same thing, same applies for "i##* " but for
-  # awk '{print $2}'. Using two of the % or # symbols means "greedy", it will
-  # only leave 1 word remaining (so if we had var="apple orange pear" and did
-  # echo "${var%% *}, it would return apple where as "${var% *}" returns all
-  # but the very last word.
-    modes[${#modes[@]}]="${i%% *}" 
-    _display_mode[${i%% *}]="${i##* }"
-  done
-  unset IFS
+        # name=$(echo "${i}" | awk '{print $1}')
+        # rest="$(echo "${i}" | awk '{print $2}')"
 
-  target=$(printf '%s\n' "${modes[@]}" | ${MENU} 'Take screenshot of:' "$@") || exit 1
-  case "$target" in
+        # Think of "i%% *" as awk '{print $1}' in this case, it isn't a 1 to 1 but
+        # for this example it does the same thing, same applies for "i##* " but for
+        # awk '{print $2}'. Using two of the % or # symbols means "greedy", it will
+        # only leave 1 word remaining (so if we had var="apple orange pear" and did
+        # echo "${var%% *}, it would return apple where as "${var% *}" returns all
+        # but the very last word.
+        modes[${#modes[@]}]="${i%% *}"
+        _display_mode[${i%% *}]="${i##* }"
+    done
+    unset IFS
+
+    target=$(printf '%s\n' "${modes[@]}" | ${MENU} 'Take screenshot of:' "$@") || exit 1
+    case "$target" in
     'Fullscreen')
-      _file_type="full"
-    ;;
+        _file_type="full"
+        ;;
     'Active window')
-      active_window=$(xdotool getactivewindow)
-      _maim_args="-i ${active_window}"
-      _file_type="window"
-    ;;
+        active_window=$(xdotool getactivewindow)
+        _maim_args="-i ${active_window}"
+        _file_type="window"
+        ;;
     'Selected region')
-      _maim_args="-s"
-      _file_type="region"
-    ;;
+        _maim_args="-s"
+        _file_type="region"
+        ;;
     *)
-      _maim_args="-g ${_display_mode[${target}]}"
-      _file_type="${target}"
-    ;;
-  esac
+        _maim_args="-g ${_display_mode[${target}]}"
+        _file_type="${target}"
+        ;;
+    esac
 
-  delay=$(printf '%s\n' "$(seq 0 5)" | ${MENU} 'Delay (in seconds):' "$@" ) || exit 1
-  if [ ! "${delay}" -eq "0" ]; then
-    _maim_args="${_maim_args} --delay=${delay}"
-  else
-    _maim_args="${_maim_args} --delay=0.5"
-  fi
+    delay=$(printf '%s\n' "$(seq 0 5)" | ${MENU} 'Delay (in seconds):' "$@") || exit 1
+    if [ ! "${delay}" -eq "0" ]; then
+        _maim_args="${_maim_args} --delay=${delay}"
+    else
+        _maim_args="${_maim_args} --delay=0.5"
+    fi
 
-  _maim_args="${_maim_args} -q"
-  local destination=( "File" "Clipboard" "Both" )
-  dest=$(printf '%s\n' "${destination[@]}" | ${MENU} 'Destination:' "$@" ) || exit 1
-  case "$dest" in
+    _maim_args="${_maim_args} -q"
+    local destination=("File" "Clipboard" "Both")
+    dest=$(printf '%s\n' "${destination[@]}" | ${MENU} 'Destination:' "$@") || exit 1
+    case "$dest" in
     'File')
-      # shellcheck disable=SC2086,SC2154
-      maim ${_maim_args} "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
-      notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
-    ;;
+        # shellcheck disable=SC2086,SC2154
+        maim ${_maim_args} "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
+        notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
+        ;;
     'Clipboard')
-      # shellcheck disable=SC2086
-      maim ${_maim_args} | cp2cb-maim
-      notify-send "Saved Screenshot" "Clipboard"
-    ;;
+        # shellcheck disable=SC2086
+        maim ${_maim_args} | cp2cb-maim
+        notify-send "Saved Screenshot" "Clipboard"
+        ;;
     'Both')
-      # shellcheck disable=SC2086
-      maim ${_maim_args} | tee "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png" | cp2cb-maim
-      notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png And Clipboard"
-    ;;
+        # shellcheck disable=SC2086
+        maim ${_maim_args} | tee "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png" | cp2cb-maim
+        notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png And Clipboard"
+        ;;
     *)
-      exit 1
-    ;;
-  esac
+        exit 1
+        ;;
+    esac
 
 }
 
@@ -148,17 +148,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@";;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
diff --git a/scripts/dm-pipewire-out-switcher b/scripts/dm-pipewire-out-switcher
--- a/scripts/dm-pipewire-out-switcher
+++ b/scripts/dm-pipewire-out-switcher
@@ -13,12 +13,12 @@
 # get hidden bugs that are hard to discover.
 set -euo pipefail
 _path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[  -f "${_path}/_dm-helper.sh" ]]; then
-  # shellcheck disable=SC1090,SC1091
-  source "${_path}/_dm-helper.sh"
+if [[ -f "${_path}/_dm-helper.sh" ]]; then
+    # shellcheck disable=SC1090,SC1091
+    source "${_path}/_dm-helper.sh"
 else
-  # shellcheck disable=SC1090
-  echo "No helper-script found"
+    # shellcheck disable=SC1090
+    echo "No helper-script found"
 fi
 
 # script will not hit this if there is no config-file to load
@@ -29,27 +29,27 @@ source "$(get_config)"
 check_updated_config
 
 get_default_sink() {
-  pactl --format=json info | jq -r .default_sink_name 
+    pactl --format=json info | jq -r .default_sink_name
 }
 get_all_sinks() {
-  pactl --format=json list short sinks |\
-    current=$(get_default_sink) jq -r '.[] | if .name == env.current then .state="* " else .state="" end | .state + .name'
+    pactl --format=json list short sinks \
+        | current=$(get_default_sink) jq -r '.[] | if .name == env.current then .state="* " else .state="" end | .state + .name'
 }
 
 main() {
-  choice=$(printf '%s\n' "$(get_all_sinks)" | \
-      sort | \
-      ${MENU} 'Sink: ' "$@") || exit 1
+    choice=$(printf '%s\n' "$(get_all_sinks)" \
+        | sort \
+        | ${MENU} 'Sink: ' "$@") || exit 1
 
-      if [ "$choice" ]; then
+    if [ "$choice" ]; then
         if [[ "${choice}" == "* $(get_default_sink)" ]]; then
-          exit 0
+            exit 0
         fi
         pactl set-default-sink "${choice}"
         notify-send "Sink is now: ${choice}"
-      else
-          echo "Program terminated." && exit 0
-      fi
+    else
+        echo "Program terminated." && exit 0
+    fi
 }
 
 noOpt=1
@@ -58,17 +58,20 @@ noOpt=1
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
     case "${arg}" in
-        d) # shellcheck disable=SC2153
-           MENU=${DMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        f) # shellcheck disable=SC2153
-           MENU=${FMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
-        r) # shellcheck disable=SC2153
-           MENU=${RMENU}
-           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@";;
-        h) help ;;
-        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    d) # shellcheck disable=SC2153
+        MENU=${DMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    f) # shellcheck disable=SC2153
+        MENU=${FMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+        ;;
+    r) # shellcheck disable=SC2153
+        MENU=${RMENU}
+        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+        ;;
+    h) help ;;
+    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
     esac
     noOpt=0
 done
