Making these scripts work with the -d, -f and -r flags for dmenu, fzf and rofi.

diff --git a/scripts/dm-record b/scripts/dm-record
--- a/scripts/dm-record
+++ b/scripts/dm-record
@@ -7,6 +7,7 @@
 # License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
 # Contributors: ashincoder
 #               HostGrady
+#               Derek Taylor
 
 # Usage:
 # `$0`: Ask for recording type via dmenu
@@ -17,15 +18,21 @@
 #
 # If there is already a running instance, user will be prompted to end it.
 
+# Set with the flags "-e", "-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 
 _path=$(dirname "$(realpath "$0")")
 [[ ! -f "${_path}/_dm-helper.sh" ]] && echo "No helper-script found"
 # shellcheck disable=SC1090,SC1091
 source "${_path}/_dm-helper.sh"
+
+# script will not hit this if there is no config-file to load
 # shellcheck disable=SC1090
 source "$(get_config)"
 
+# Check if config has updates that should be displayed to the user
 check_updated_config
 
 killrecording() {
@@ -92,7 +99,7 @@ audio() { \
 # TODO: deprecate or rewrite
 
 askrecording() {
-	choice="$(printf "screencast\\nvideo\\nvideo selected\\naudio\\nwebcam\\nwebcam (hi-def)" | ${DMENU} "Select recording style:")"
+	choice="$(printf "screencast\\nvideo\\nvideo selected\\naudio\\nwebcam\\nwebcam (hi-def)" | ${MENU} "Select recording style:")"
 	
 	case "$choice" in
 		screencast) screencast;;
@@ -105,7 +112,7 @@ askrecording() {
 	}
 
 asktoend() { \
-	response=$(printf "No\\nYes" | ${DMENU} "Recording still active. End recording?") &&
+	response=$(printf "No\\nYes" | ${MENU} "Recording still active. End recording?") &&
 	[ "$response" = "Yes" ] &&  killrecording
 	}
 
@@ -137,5 +144,26 @@ main() {
 	esac
 }
 
+noOpt=1
+# If script is run with '-d', it will use 'dmenu'
+# If script is run with '-f', it will use 'fzf'
+# If script is run with '-d', it will use 'rofi'
+while getopts "dfrh" arg 2>/dev/null; do
+    case "${arg}" in
+        d) # shellcheck disable=SC2153
+           MENU=${DMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        f) # shellcheck disable=SC2153
+           MENU=${FMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        r) # shellcheck disable=SC2153
+           MENU=${RMENU}
+           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
+        h) help ;;
+        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+    esac
+    noOpt=0
+done
 
-[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+# If script is run with NO argument, it will use 'dmenu'
+[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
